'use strict';
// Builds icons.js from the user's Tana line icon set (Nucleo export). Run: node scripts/build-icons.js
// Colours are stripped to currentColor so CSS controls the grey.
const fs = require('node:fs');
const path = require('node:path');
const SRC = process.argv[2] || '/Users/andre.foeken/Documents/Tana icons (line)';
const WANT = { task: 'list-checkbox.svg', calendar: 'calendar.svg' };
const out = {};
for (const [name, file] of Object.entries(WANT)) {
  let svg = fs.readFileSync(path.join(SRC, file), 'utf8');
  svg = svg.replace(/<title>.*?<\/title>/, '')
    .replace(/^<svg[^>]*>/, (tag) => tag.replace(/\s(height|width)="[^"]*"/g, ''))
    .replace(/(stroke|fill)="#[0-9a-fA-F]{3,6}"/g, '$1="currentColor"').replace(/>\s+</g, '><').trim();
  out[name] = svg;
}
const js = '// Generated by scripts/build-icons.js from the Tana line icon set (Nucleo). Do not edit by hand.\n'
  + 'window.ICONS = ' + JSON.stringify(out, null, 2) + ';\n';
fs.writeFileSync(path.join(__dirname, '..', 'icons.js'), js);
console.log('wrote icons.js', Object.keys(out).join(', '));
