'use strict';
// Builds icons.js from the user's Tana line icon set (Nucleo export). Run: node scripts/build-icons.js
// Colours are stripped to currentColor so CSS controls the grey.
const fs = require('node:fs');
const path = require('node:path');
const SRC = process.argv[2] || '/Users/andre.foeken/Documents/Tana icons (line)';
const WANT = { task: 'list-checkbox.svg', calendar: 'calendar.svg', sync: path.join(__dirname, '..', 'build', 'icons', 'cloud-refresh.svg'), doc: path.join(__dirname, '..', 'build', 'icons', 'report-file.svg'), space: path.join(__dirname, '..', 'build', 'icons', 'box-archive-3.svg'), member: path.join(__dirname, '..', 'build', 'icons', 'circle-user.svg'), lock: path.join(__dirname, '..', 'build', 'icons', 'lock.svg'), userLock: path.join(__dirname, '..', 'build', 'icons', 'user-lock.svg'), houseLock: path.join(__dirname, '..', 'build', 'icons', 'house-lock.svg'), users: path.join(__dirname, '..', 'build', 'icons', 'users-3.svg'), library: path.join(__dirname, '..', 'build', 'icons', 'bookmarked-book.svg'), pin: path.join(__dirname, '..', 'build', 'icons', 'pin.svg'), pinDate: path.join(__dirname, '..', 'build', 'icons', 'calendar-pin.svg'), any: path.join(__dirname, '..', 'build', 'icons', 'pop.svg'), setIcon: path.join(__dirname, '..', 'build', 'icons', 'images-3.svg'), darkLight: path.join(__dirname, '..', 'build', 'icons', 'dark-light.svg'), unassigned: path.join(__dirname, '..', 'build', 'icons', 'circle-dotted-user.svg'), createNew: path.join(__dirname, '..', 'build', 'icons', 'square-dashed-plus.svg'), apply: path.join(__dirname, '..', 'build', 'icons', 'check-2.svg'), field: path.join(__dirname, '..', 'build', 'icons', 'text-input.svg'), type: path.join(__dirname, '..', 'build', 'icons', 'shapes.svg'), inbox: path.join(__dirname, '..', 'build', 'icons', 'inbox.svg'), video: path.join(__dirname, '..', 'build', 'icons', 'video.svg') };
const out = {};
for (const [name, file] of Object.entries(WANT)) {
  let svg = fs.readFileSync(path.isAbsolute(file) ? file : path.join(SRC, file), 'utf8');
  svg = svg.replace(/<title>.*?<\/title>/, '')
    .replace(/^<svg[^>]*>/, (tag) => tag.replace(/\s(height|width)="[^"]*"/g, ''))
    .replace(/(stroke|fill)="#[0-9a-fA-F]{3,6}"/g, '$1="currentColor"').replace(/>\s+</g, '><').trim();
  out[name] = svg;
}
const js = '// Generated by scripts/build-icons.js from the Tana line icon set (Nucleo). Do not edit by hand.\n'
  + 'window.ICONS = ' + JSON.stringify(out, null, 2) + ';\n';
fs.writeFileSync(path.join(__dirname, '..', 'icons.js'), js);
console.log('wrote icons.js', Object.keys(out).join(', '));
