'use strict';
// Generic accessors for the common 'data' map and the ProseMirror-style 'content' map (protocol doc §3).

const STATE_TYPES = ['proposed', 'open', 'closed', 'not_now'];

function readNode(document) {
  return Object.assign({ id: document.id }, document.data.toJSON());
}

// Exactly what the web client's setTitle writes: title plus removal of titleAutoGenerated.
function setTitle(document, title) {
  document.transact((loro) => {
    const data = loro.getMap('data');
    data.set('title', title);
    data.delete('titleAutoGenerated');
  });
}

// transitionTo(stateType, changedBy) for plain (non-workflow) states.
function setState(document, stateType, byUri) {
  if (!STATE_TYPES.includes(stateType)) throw new Error('unknown stateType ' + stateType);
  if (!/^tana:user-profile:/.test(byUri || '')) throw new Error('stateChangedBy must be a tana:user-profile: URI');
  document.transact((loro) => {
    const data = loro.getMap('data');
    data.set('stateType', stateType);
    data.set('stateEnteredAt', Date.now());
    data.set('stateChangedBy', byUri);
    data.delete('stateWorkflowUri');
    data.delete('stateWorkflowStateId');
  });
}

function contentText(document) {
  return render(document.content.toJSON());
}

// ponytail: block vs inline is inferred (a node with non-mention child nodes is a block container); add an
// explicit node-name table if the editor schema turns out to have inline nodes with children.
function render(node) {
  if (typeof node === 'string') return node;
  if (!node || typeof node !== 'object') return '';
  if (node.nodeName === 'mention') return (node.attributes && node.attributes.label) || '';
  const kids = Array.isArray(node.children) ? node.children : [];
  const block = kids.some((k) => k && typeof k === 'object' && k.nodeName !== 'mention');
  return kids.map(render).join(block ? '\n' : '');
}

module.exports = { readNode, setTitle, setState, contentText, STATE_TYPES };
