'use strict';
// Generic accessors for the common 'data' map and the ProseMirror-style 'content' map (protocol doc §3).
const { randomBytes } = require('node:crypto');
const { LoroMap, LoroList } = require('loro-crdt');

const STATE_TYPES = ['proposed', 'open', 'closed', 'not_now'];
const B32 = '0123456789abcdefghjkmnpqrstvwxyz'; // Crockford base32, lowercase as in Tana ids

// 26-char ULID: 48-bit ms timestamp + 80 random bits.
function ulid(now = Date.now()) {
  let s = '', t = now;
  for (let i = 0; i < 10; i++) { s = B32[t % 32] + s; t = Math.floor(t / 32); }
  for (const b of randomBytes(16)) s += B32[b % 32];
  return s;
}

// The data map of a new document as the web client creates it plus an empty content skeleton. Run inside
// Document.transact. kind 'doc' (default): a plain text document (scripts/fixtures/task-snapshot.b64 minus the
// task fields); 'task': plus the open state assigned to byUri; 'meeting': a 'tana:event:' document laid out like a
// Tana-created event (tana:event:01m1xcnjbykczkxj8x03ttkcad, without the calendar-provider fields), starting at
// the next half hour for 30 minutes.
function initDocument(loro, title, byUri, { kind = 'doc', now = Date.now() } = {}) {
  if (!['doc', 'task', 'meeting'].includes(kind)) throw new Error('unknown kind ' + kind);
  const data = loro.getMap('data');
  data.set('type', kind === 'meeting' ? 'event' : 'text');
  data.set('title', title);
  data.set('createdAt', now);
  data.set('restricted', true);
  const p = data.setContainer('participants', new LoroMap()).setContainer(byUri, new LoroMap());
  p.set('type', 'user');
  p.set('role', 'admin');
  data.setContainer('sharedPinDates', new LoroList());
  if (kind === 'meeting') {
    const start = Math.ceil(now / 18e5) * 18e5;
    data.set('startTime', start);
    data.set('endTime', start + 18e5);
    data.set('timezone', Intl.DateTimeFormat().resolvedOptions().timeZone);
    data.set('origin', 'tana');
    data.setContainer('attendees', new LoroList());
  } else {
    data.setContainer('attributes', new LoroMap());
  }
  if (kind === 'task') {
    data.set('stateType', 'open');
    data.set('stateEnteredAt', now);
    data.set('stateChangedBy', byUri);
    data.setContainer('assignedToUris', new LoroList()).push(byUri);
    data.set('assignedToUrisChangedAt', now);
    data.set('assignedToUrisChangedBy', byUri);
  }
  const c = loro.getMap('content');
  c.set('nodeName', 'doc');
  c.setContainer('attributes', new LoroMap());
  c.setContainer('children', new LoroList());
}

function readNode(document) {
  return Object.assign({ id: document.id }, document.data.toJSON());
}

// Exactly what the web client's setTitle writes: title plus removal of titleAutoGenerated.
function setTitle(document, title) {
  document.transact((loro) => {
    const data = loro.getMap('data');
    data.set('title', title);
    data.delete('titleAutoGenerated');
  });
}

// transitionTo(stateType, changedBy) for plain (non-workflow) states.
function setState(document, stateType, byUri) {
  if (!STATE_TYPES.includes(stateType)) throw new Error('unknown stateType ' + stateType);
  if (!/^tana:user-profile:/.test(byUri || '')) throw new Error('stateChangedBy must be a tana:user-profile: URI');
  document.transact((loro) => {
    const data = loro.getMap('data');
    data.set('stateType', stateType);
    data.set('stateEnteredAt', Date.now());
    data.set('stateChangedBy', byUri);
    data.delete('stateWorkflowUri');
    data.delete('stateWorkflowStateId');
  });
}

function contentText(document) {
  return render(document.content.toJSON());
}

// ponytail: block vs inline is inferred (a node with non-mention child nodes is a block container); add an
// explicit node-name table if the editor schema turns out to have inline nodes with children.
function render(node) {
  if (typeof node === 'string') return node;
  if (!node || typeof node !== 'object') return '';
  if (node.nodeName === 'mention') return (node.attributes && node.attributes.label) || '';
  const kids = Array.isArray(node.children) ? node.children : [];
  const block = kids.some((k) => k && typeof k === 'object' && k.nodeName !== 'mention');
  return kids.map(render).join(block ? '\n' : '');
}

module.exports = { readNode, setTitle, setState, contentText, ulid, initDocument, STATE_TYPES };
